name: Cold Cocoa
version: 1  
referenceUrls: https://www.chewoutloud.com/easy-chocolate-ice-cream-eggs/  
creamiProductType: original  
ingredients:  
  - 3/4 c, unsweetened cocoa powder  
  - 1/3 c, brown sugar
  - 1/2 c, white sugar  
  - 1 1/2 c, whole milk  
  - 2 c, heavy cream
  - 2 tsp, vanilla extract
steps:  
  - In a chilled bowl, combine cocoa and both sugars, whisking to combine well.  
  - Add cold milk and whisk until sugars are dissolved.  
  - Stir in cold heavy cream and vanilla.  
  - Pour mixture into the freezer bowl of ice cream maker. Let run for 25-30 minutes, or until mixture is thick, soft, and creamy.  
  - Transfer to airtight container and freeze at least 2 hours or until ice cream reaches desired consistency.  
  - Prior to serving, let ice cream sit at room temp for a few minutes just to soften enough for easy scooping.  
notes:  
  - date: 01/19/25  
    version: 1  
    text: No changes next time.
score:  
  texture: 22
  flavor: 20