name: Peanut Butter Banana
version: 1
referenceUrls: 
  - https://www.reddit.com/r/Volumeeating/comments/trsmp3/peanut_butter_banana_ice_cream_in_the_ninja/?utm_source=share&utm_medium=web2x&context=3
creamiProductType: original
ingredients:
  - 1, banana
  - 1/2 tbsp, banana creme pudding
  - 1 tbsp, Pb Fit
  - 1/4 tsp, vanilla
  - 1 c, Fairlife 2% milk
  - 1, pinch of salt
  - 1/4 c, semi-sweet chocolate chips
steps:
  - Mix all ingredients with an immersion blender, except for chocolate chips.
  - Pour into pint and freeze for 24 hours.
  - Take the pint out of freezer, let sit out on the counter for 10 mins.
  - Run sides under hot water for 30 secs.
  - Install pint, choose Light Ice Cream and spin the pint.
  - Use a spoon to create a hole to the bottom of the pint, add chocolate chips.
  - Install pint and choose MIX-IN spin.
notes:
  - date: 02/19/24
    version: 1
    # versionLink: 
    text: Next time would like to add more Pb Fit (at least a serving), also would maybe add peanut butter. Another thought was to sub pudding for a non-flavored binder (the banana flavor seemed overpowering).
score:
  texture: 33
  flavor: 27


