name: Peanut Butter Chocolate Banana Protein
# referenceUrls: 
creamiProductType: deluxe
ingredients:
  - 1, banana
  - 1/4 tsp, xanthan gum
  - 1 tsp, cocoa powder
  - 3 tbsp, Pb Fit
  - 1, 16 oz fairlife chocolate protein shake
steps:
  - Mix all ingredients with an immersion blender, except portein shake.
  - Pour ingredients up to max fill line.
  - Take the pint out of freezer, let sit out on the counter for 5 mins.
  - Run sides under hot water for 30 secs.
  - Install pint, choose Light Ice Cream and spin the pint. (Was still powdery, so did one re-spin).
notes:
  - date: 03/13/24
    text: Increase amount of banana and pb fit.
