name: Vanilla Protein
referenceUrls: 
  - https://bykelseysmith.com/ninja-creami-vanilla-protein-ice-cream/
creamiProductType: deluxe
ingredients:
  - 21 oz, Fairlife Core Power Vanilla Protein Shake
  - 2 tbsp, stevia
  - 2 tbsp, sugar free instant vanilla pudding mix
steps:
  - Using an immersion blender, mix all ingredients.
  - Pour into pint and freeze.
  - Take the pint out of freezer, let sit out on the counter for 15 mins.
  - Run sides under hot water for 30 secs.
  - Install pint, choose Light Ice Cream and spin the pint.
  - The pint was still crumbly after the first spint, one re-spin got it to the right consistency.
notes:
  - date: 02/08/24
    text: I enjoyed the flavor of the Fairlife shake more than the muscle milk shakes. Texture was marginably better. For next spin, thinking about replacing the pudding mix with a different non-flavored binder. After reviewing the source recipe, the standard pint and deluxe pint measurements are not scaling appropriately. Next spin should plan to update the recipe to 'original pint', and set to 14 oz shake, 1 tbsp stevia, and 1 tablespoon pudding mix. The app will scale appropriately for the deluxe pint conversion (.5 tbsp less sweetener and pudding mix which I think will improve taste).
  - date: 01/26/24
    text: Very prevelant protein taste. Icy on sides. Next time plan to use Fairlife and run hot water on sides of pint.
score:
  texture: 13
  flavor: 12
