name: High Protein Vanilla
version: 1
referenceUrls: 
  - https://bykelseysmith.com/ninja-creami-vanilla-protein-ice-cream/
creamiProductType: deluxe
ingredients:
  - 21 oz, Muscle Milk Vanilla Protein Shake
  - 2 tbsp, stevia
  - 2 tbsp, sugar free instant vanilla pudding mix
steps:
  - 1. Using an immersion blender, mix all ingredients.
  - 2. Pour into pint and freeze.
  - 3. Take the pint out of freezer, let sit out on the counter for 15 .
  - 4. Install pint, choose Light Ice Cream and spin the pint.
  - 5. If crumbly, re-spin.
notes:
  - date: 01/26/24
    version: 1
    text: Very prevelant protein taste. Icey on sides. Next time plan to use Fairlife and run hot water on sides of pint.
score:
  texture: 28
  flavor: 20


