name: Cookies and Cream
version: 1
referenceUrls: 
  - https://www.chewoutloud.com/cookies-and-cream-ice-cream/
creamiProductType: deluxe
ingredients:
  - 2 c, heavy cream
  - 1 c, 2% milk
  - 3/4 c, granulated sugar
  - 2 tsp, vanilla extract
  - 12, Double Stuffed Oreos
steps:
  - Break up Oreos and freeze before hand.
  - Mix remaining ingredients with immersion blender. Let mixture sit in fridge overnight or at least a few hours.
  - Give quick stur and churn the vanilla base.
  - Once churned, pour in Oreos before completing. Churned for a few mins to mix in.
notes:
  - date: 08/27/24
    version: 1
    # versionLink: 
    text: Made in ice-21. Next churn plan to layer Oreos rather than churning all within base. Also try more Oreos but regular rather than Double Stuffed.
score:
  texture: 21
  flavor: 22