name: Rhubarb Swirl
referenceUrls: 
  - https://www.reddit.com/r/icecreamery/s/J7XIvB1JYF
productType: CREAMi Deluxe
ingredients:
  - 2 c, heavy cream
  - 1 c, 2% milk
  - 3/4 c, granulated sugar
  - 1 tbsp, vanilla extract
  - 1, pinch salt
  - 1/2 c, strawberry rhubarb jam
steps:
  - Mix all ingredients except jam with immersion blender. Let mixture sit in fridge overnight.
  - Next day, churn the vanilla base.
  - In a storage container, scoop ice cream in. Then scoop in rhubarb jelly, covering the ice cream creating a thin layer. Continue alternating, should have at least three layers of rhubarb jam.
  - Best to freeze for at least a couple hours before scooping.
notes:
  - date: 08/15/24
    text: Made in ice-21. Great after two hours. Will be interesting to see how it will hold after a few days.
  - date: 09/28/24
    text: Tested same recipe with Les Tres recipe. I think first version is preferred, but also turned out good.
