name: Peanut Butter Banana
referenceUrls: 
  - https://www.reddit.com/r/Volumeeating/comments/trsmp3/peanut_butter_banana_ice_cream_in_the_ninja/?utm_source=share&utm_medium=web2x&context=3
creamiProductType: original
ingredients:
  - 2, bananas
  - 1/2 tbsp, banana creme pudding
  - 2 1/2 tbsp, Pb Fit
  - 1/4 tsp, vanilla
  - 1 c, 2% milk
  - 1, pinch of salt
  - 2 tbsp, Peanut Butter
  - 6, Reese's Thins
steps:
  - Mix all ingredients with an immersion blender, except for chocolate chips.
  - Pour into pint and freeze for 24 hours.
  - Take the pint out of freezer, let sit out on the counter for 5 mins.
  - Run sides under hot water for 30 secs.
  - Install pint, choose Light Ice Cream and spin the pint. (Was still powdery, so did one re-spin).
  - Use a spoon to create a hole to the bottom of the pint, add Reese's Thins and peanut butter.
  - Install pint and choose MIX-IN spin.
notes:
  - date: 03/23/24
    text: Instead of Peanut Butter, tried Reese's Thins. Next time, add back pb. Thins were good, but actual cups may be better. Instead of adding PB as mix-in, add into base next time.
  - date: 03/09/24
    text: Extra peanut butter improved texture and taste. Dark chocolate did not pair well, milk chocolate best for next time.
  - date: 03/03/24
    text: Slightly icey. Next time increase amount of peanut butter mix-in. Use non-mini chocolate chips. Swap banana creme pudding with another non-flavored binder. 
  - date: 02/19/24
    text: Next time would like to add more Pb Fit (at least a serving), also would maybe add peanut butter. Another thought was to sub pudding for a non-flavored binder (the banana flavor seemed overpowering).
