name: High Protein Vanilla
version: 1
referenceUrls: 
  - https://bykelseysmith.com/ninja-creami-vanilla-protein-ice-cream/
revisions: []
creamiProductType: deluxe
ingredients:
  - 21 oz, Fairlife Core Power Vanilla Protein Shake
  - 2 tbsp, stevia
  - 2 tbsp, sugar free instant vanilla pudding mix
steps:
  - 1. Mix all ingredients
  - 2. Pour into pint and freeze
