name: Cake Batter
referenceUrls: 
  - https://idreamoficecream.com/ninja-creami-cake-batter-ice-cream/
productType: CREAMi Original
ingredients:
  - 1 1/2 c, whole milk
  - 4 tbsp, instant vanilla pudding mix
  - 1/2 c, heavy whipping cream
  - 1 tsp, cake batter flavor extract
  - 1/4 c, sprinkles
  - 4, frosted animal crackers
steps:
  - Using an immersion blender, mix all ingredients.
  - Pour into pint and freeze for 24 hours.
  - Take the pint out of freezer, run pint under hot water for 15 seconds.
  - Install pint, choose Ice CREAM and spin. Required 2-3 re-spins.
  - Using a spoon, make a hole reaching the bottom of the pint. Add sprinkles and animal crackers. Install the pint. Choose MIX-IN setting and spin.
notes:
  - date: 04/06/24
    text: Next time try without vanilla pudding mix, instead use another thickener and sweetener.
  - date: 01/29/24
    text: I would like to try this recipe again with running sides of pint under hot water before spinning. Adding cake pieces (or maybe sugar cookies) to the pint would be also something I would like to try. Realized that cake batter extract is not so easy to find.
