name: Canned Peaches
referenceUrls: 
  - https://ninjatestkitchen.com/recipe/easy-peach-sorbet/
creamiProductType: original
ingredients:
  - 24 oz, canned Kirkland sliced peaches (in light syrup)
steps:
  - Using an immersion blender, blend the canned peaches.
  - Pour into pint and freeze for 24 hours.
  - Take the pint out of freezer, let sit out on the counter for 15 mins.
  - Run sides of pint under hot water for 30 secs.
  - Install pint, choose SORBET and spin.
notes:
  - date: 08/04/24
    text: No changes to recipe. First recipe made with Cuisinart Ice-21. The texture was better than Ninja Creami. Took less than 15 mins to get desired texture.
  - date: 04/21/24
    text: No changes for next spin.
  - date: 02/03/24
    text: The sourced recipe uses 20 oz canned peaches, should increase the amount next time around. Would like to add stevia in next spin to improve sweetness.
score:
  texture: 21
  flavor: 19
