name: Vanilla
referenceUrls: 
  - https://ninjatestkitchen.com/recipe/vanilla-ice-cream-with-chocolate-chips/
creamiProductType: deluxe
ingredients:
  - 1 1/2 tbsp, cream cheese
  - 1/2 c, granulated sugar
  - 1 1/2 tsp, vanilla extract
  - 3/4 c, heavy cream
  - 2 c, 2% Milk
steps:
  - Soften cream cheese.
  - Mix all ingredients with an immersion blender.
  - Pour into pint, up to the max fill line, and freeze for 24 hours.
  - Take the pint out of freezer and immediately run sides under hot water for 15 secs.
  - Install pint, choose Ice Cream, and spin.
  - Pint was crumbly, required a re-spin.
notes:
  - date: 03/02/24
    text: Ran out of heavy cream while making recipe - increased 2% milk used. Icey. Next time try v1 ingredients and increase vanilla.
  - date: 02/10/24
    text: Not going to score. Ended up being very soupy - spun too many times - along with allowing to sit out for too long. We will attempt this recip again - with real cream cheese and a shorter wait out period on the counter.
score:
  texture: 12
  flavor: 14
