v1:
  name: Classic Vanilla
  source_urls: 
    - https://ninjatestkitchen.com/recipe/vanilla-ice-cream-with-chocolate-chips/
  revisions: []
  product: deluxe
  ingredients:
    - 1.5 tablespoons, cream cheese
    - .5 cup, granulated sugar
    - 1.5 teaspoons, vanilla extract
    - 1 cup + 2 tablespoons, heavy cream
    - 1.5 cups whole milk
  steps:
    - Soften cream cheese
    - Mix all ingredients
    - Pour into pint and freeze
