name: Cookies and Cream Protein
referenceUrls: 
  - https://www.youtube.com/watch?v=HbvidbBT-iA
productType: CREAMi Original
ingredients:
  - 4, oreo cookies
  - 410 g, 2% milk
  - 4 g, vanilla extract
  - 1, scoop vanilla whey protein
  - 10 g, Swerve
  - 4 g, cocoa powder
  - 1 g, salt
  - 1 g, xanthan gum
steps:
  - In a high-sided container, add a single oreo along with wet ingredients.
  - In another bowl, mix all dry ingredients.
  - Slowly pour in dry ingredients into the wet container while mixing with an immersion blender.
  - Pour into pint, up to the max fill line, and freeze for 24 hours.
  - To prepare the oreos that will be used as mix-ins, dunk the remaining oreos in milk for about 10 seconds. Remove and place in sandwich bag. Immediately place in freezer.
  - Take the pint out of freezer, let sit out on the counter for 5 mins.
  - Run sides under hot water for 30 secs.
  - Install pint, choose SORBET setting and spin.
  - Take the remaining oreos from the freezer (except for 1). Cut them in about 1/4 size chunks. Create a hole in the pint that is off-center. Fill with oreos. Re-install the pint and choose MIX-INS.
  - Use the remaining oreo as a topping.
notes:
  - date: 04/06/23
    text: Prep more oreos for topping. Mix-in oreos were pulverized, maybe use a mix of soaked and non-soaked for mix in next time.
