name: Classic Vanilla
version: 1
referenceUrls: 
  - https://ninjatestkitchen.com/recipe/vanilla-ice-cream-with-chocolate-chips/
revisions: []
creamiProductType: deluxe
ingredients:
  - 1 1/2 tbsp, cream cheese
  - 1/2 c, granulated sugar
  - 1 1/2 tsp, vanilla extract
  - 1 c + 2 tbsp, heavy cream
  - 1 1/2 c, whole milk
steps:
  - 1. Soften cream cheese
  - 2. Mix all ingredients
  - 3. Pour into pint and freeze
