name: Lemon Pie
creamiProductType: original
ingredients:
  - 1 tsp, lemon extract
  - 1/2 c, heavy whipping cream
  - 3/4 c, 2% milk
  - 3/4 c, lemon pie filling
  - 2 tbsp, Swerve
  - 4, graham cracker squares
steps:
  - Mix all ingredients with an immersion blender, except the graham crackers.
  - Pour into pint, up to the max fill line, and freeze for 24 hours.
  - Pour a small glass of milk and soak each graham cracker square for about a second. Store in a sandwich bag and place in freezer.
  - Take the pint out of freezer and immediately run sides under hot water for 15 secs.
  - Install pint, choose Ice Cream, and spin.
  - Take crackers out and chop up, add as a topping.
notes:
  - date: 03/30/24
    text: Pre-soaked 4 graham cracker squares in milk and froze before chopping and adding as topping. Incorporate cream cheese next time?
  - date: 03/26/24
    text: Too much vanilla flavor. Graham crackers did not add much.
score:
  texture: 21
  flavor: 20