name: Lemon Pie
version: 2
creamiProductType: original
ingredients:
  - 1 tsp, lemon extract
  - 1/2 c, heavy whipping cream
  - 3/4 c, 2% milk
  - 3/4 c, lemon pie filling
  - 2 tbsp, Swerve
steps:
  - Mix all ingredients with an immersion blender, except the graham crackers.
  - Pour into pint, up to the max fill line, and freeze for 24 hours.
  - Take the pint out of freezer and immediately run sides under hot water for 15 secs.
  - Install pint, choose Ice Cream, and spin.
notes:
  - date: 
    version: 2
    # versionLink: 
    text:
  - date: 
    version: 1
    # versionLink: 
    text: Too much vanilla flavor. Graham crackers did not add much.
score:
  texture: 40
  flavor: 36