name: Cake Batter
version: 1
referenceUrls: 
  - https://idreamoficecream.com/ninja-creami-cake-batter-ice-cream/
creamiProductType: original
ingredients:
  - 1 1/2 c, whole milk
  - 4 tbsp, instant vanilla pudding mix
  - 1/2 c, heavy whipping cream
  - 1 tsp, cake batter flavor extract
  - 1/4 c, sprinkles
steps:
  - Using an immersion blender, mix all ingredients.
  - Pour into pint and freeze for 24 hours.
  - Take the pint out of freezer, let sit out on the counter for 5 mins.
  - Install pint, choose Ice CREAM and spin.
  - Using a spoon, make a hole reaching the bottom of the pint. Add sprinkles. Install the pint. Choose MIX-IN setting and spin.
notes:
  - date: 01/29/24
    version: 1
    # versionLink:
    text: I would like to try this recipe again with running sides of pint under hot water before spinning. Adding cake pieces (or maybe sugar cookies) to the pint would be also something I would like to try. Realized that cake batter extract is not so easy to find.
score:
  texture: 30
  flavor: 32
